import { StyleSheet } from 'react-native';
import { palette } from '../../theme';

/** Shared bottom-sheet styles for the My Page modals. */
export const sheetStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: palette.overlay, justifyContent: 'flex-end' },
  card: {
    backgroundColor: palette.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: '82%',
    borderWidth: 1,
    borderColor: palette.border,
    borderBottomWidth: 0,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: palette.border,
  },
  titleRow: { flexDirection: 'row', alignItems: 'center' },
  title: { fontSize: 18, fontWeight: '800', color: palette.text },
  content: { paddingBottom: 20 },
  welcome: {
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 24,
    backgroundColor: palette.surfaceAlt,
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: palette.border,
  },
  settingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  settingText: { flex: 1, paddingRight: 15 },
  settingTitle: { color: palette.text, fontSize: 14, fontWeight: '700', marginBottom: 4 },
  settingDesc: { color: palette.textDim, fontSize: 12, lineHeight: 16 },
  divider: { height: 1, backgroundColor: palette.border, marginVertical: 18 },
  toggle: { width: 44, height: 24, borderRadius: 12, padding: 2, justifyContent: 'center' },
  toggleOn: { backgroundColor: palette.accent },
  toggleOff: { backgroundColor: palette.borderStrong },
  toggleDot: { width: 20, height: 20, borderRadius: 10, backgroundColor: palette.text },
  dotOn: { alignSelf: 'flex-end' },
  dotOff: { alignSelf: 'flex-start' },
  closeBtn: {
    backgroundColor: palette.accent,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 10,
  },
  closeBtnText: { color: palette.accentInk, fontSize: 14, fontWeight: '700' },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12, marginBottom: 4 },
  chip: {
    backgroundColor: palette.border,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  chipActive: { backgroundColor: palette.accentWash, borderColor: palette.accent },
  chipText: { color: palette.textMuted, fontSize: 12, fontWeight: '600' },
  chipTextActive: { color: palette.accent },
  timerSection: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: palette.border,
  },
  timerLabel: { color: palette.accent, fontSize: 12, fontWeight: '700', marginBottom: 8 },
  timerChipRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap' },
  timerChip: {
    backgroundColor: palette.border,
    borderWidth: 1,
    borderColor: palette.borderStrong,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 6,
  },
  timerChipActive: { backgroundColor: palette.accentWash, borderColor: palette.accent },
  timerChipCancel: { backgroundColor: 'rgba(255, 59, 48, 0.12)', borderColor: palette.danger },
  timerChipText: { color: palette.textMuted, fontSize: 12, fontWeight: '600' },
  timerChipTextActive: { color: palette.accent },
  timerChipTextCancel: { color: palette.danger, fontSize: 12, fontWeight: '600' },
});
